data:
  train_t_path: data/proc_train_t
  train_v_path: data/proc_train_v
  train_c_path: data/proc_train_c
  temp_dir: tmp
training: null
model:
  name: xgboost
xgboost:
  n_estimators: 293
  early_stopping_rounds: 20
  max_depth: 6
  learning_rate: 0.037304761898752176
  subsample: 1.0
  colsample_bytree: 0.6351227643858766
  scale_pos_weight: null
  gpu_id: 0
  verbosity: 0
  seed: 42
  tree_method: gpu_hist
  use_mixup: false
  min_child_weight: 7
  gamma: 1.241565369269177
  reg_alpha: 1.925105128912058
  reg_lambda: 1.4570210990841745
  max_bin: 221
  calibration_method: sigmoid
catboost:
  iterations: 200
  learning_rate: 0.1
  depth: 8
  subsample: 1
  colsample_bylevel: 0.8
  task_type: GPU
  devices: '0'
  verbose: false
  early_stopping_rounds: 20
  thread_count: -1
  random_seed: 42
  bootstrap_type: Bernoulli
  use_mixup: false
  mixup_alpha: 0.3
  mixup_ratio: 0.5
presets:
  xgboost:
    model:
      name: xgboost
  catboost:
    model:
      name: catboost
