data:
  train_t_path: data/train_t.parquet
  train_v_path: data/train_v.parquet
  temp_dir: tmp
training: null
model:
  name: xgboost
xgboost:
  n_estimators: 186
  learning_rate: 0.2511367755155965
  max_depth: 19
  subsample: 1.0
  colsample_bytree: 0.9963115111382519
  tree_method: gpu_hist
  gpu_id: 0
  verbosity: 0
  early_stopping_rounds: 20
  seed: 42
  min_child_weight: 2
  gamma: 0.011655401502024312
  reg_alpha: 2.6271450275232193
  reg_lambda: 0.11457500170538186
  max_bin: 251
  use_mixup: true
  mixup_alpha: 0.6
  mixup_ratio: 0.30000000000000004
  calibration_method: temperature
catboost:
  iterations: 200
  learning_rate: 0.1
  depth: 8
  subsample: 1
  colsample_bylevel: 0.8
  task_type: GPU
  devices: '0'
  verbose: false
  early_stopping_rounds: 20
  thread_count: -1
  random_seed: 42
  bootstrap_type: Bernoulli
  use_mixup: false
  mixup_alpha: 0.3
  mixup_ratio: 0.5
presets:
  xgboost:
    model:
      name: xgboost
  catboost:
    model:
      name: catboost
