data:
  train_path: /data1/seunghoon/train.parquet
  temp_dir: tmp
cv:
  n_folds: 5
  force_reprocess: false
model:
  name: xgboost
xgboost:
  n_estimators: 200
  learning_rate: 0.1
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  tree_method: gpu_hist
  gpu_id: 0
  verbosity: 0
  early_stopping_rounds: 20
  random_state: 42
catboost:
  n_estimators: 383
  learning_rate: 0.010725209743171997
  max_depth: 10
  subsample: 0.6061695553391381
  colsample_bylevel: 0.8
  task_type: GPU
  devices: '0'
  verbose: false
  early_stopping_rounds: 20
  thread_count: -1
  random_state: 42
  bootstrap_type: MVS
  l2_leaf_reg: 8.491983767203795
  border_count: 149
presets:
  xgboost_fast:
    model:
      name: xgboost
    xgboost:
      n_estimators: 100
      learning_rate: 0.15
      max_depth: 6
  xgboost_deep:
    model:
      name: xgboost
    xgboost:
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 10
  catboost_fast:
    model:
      name: catboost
    catboost:
      n_estimators: 100
      learning_rate: 0.15
      max_depth: 6
  catboost_deep:
    model:
      name: catboost
    catboost:
      n_estimators: 300
      learning_rate: 0.05
      max_depth: 10
