# 기본 훈련 설정
BATCH_SIZE: 2048
EPOCHS: 1  # XGBoost는 에포크 기반이 아니므로 1로 설정
LEARNING_RATE: 0.1
WEIGHT_DECAY: 0.00001
SEED: 42

# Warmup 설정 (XGBoost에서는 사용하지 않음)
WARMUP:
  ENABLED: false
  WARMUP_EPOCHS: 0

# 검증 데이터 분할 비율
VAL_SPLIT: 0.2

# Early Stopping 설정 (XGBoost 내장 early stopping 사용)
EARLY_STOPPING:
  ENABLED: false  # XGBoost 내장 early stopping 사용
  PATIENCE: 5
  MIN_DELTA: 0.00001
  MONITOR: "val_score"
  MODE: "max"
  RESTORE_BEST_WEIGHTS: false

# 메트릭 설정
METRICS:
  SAVE_LOGS: true        # 훈련 로그 저장 여부
  LOG_FILE: "train_logs.csv"  # 로그 파일명

# Gradient Norm 설정 (XGBoost에서는 사용하지 않음)
GRADIENT_NORM:
  ENABLED: false
  SAVE_LOGS: false
  LOG_FILE: "gradient_norms.csv"
  COMPONENTS: []

# 모델 설정 - XGBoost 사용
MODEL:
  # TabularTransformer 모델 설정 (사용하지 않지만 호환성을 위해 유지)
  TRANSFORMER:
    HIDDEN_DIM: 64            # Transformer hidden dimension
    N_HEADS: 8                # Number of attention heads
    N_LAYERS: 3               # Number of transformer layers
    FFN_SIZE_FACTOR: 1.333    # FFN size factor (4/3)
    ATTENTION_DROPOUT: 0.2    # Attention dropout rate
    FFN_DROPOUT: 0.2          # FFN dropout rate
    RESIDUAL_DROPOUT: 0.0     # Residual dropout rate
    
  # XGBoost 모델 설정
  XGBOOST:
    N_ESTIMATORS: 1000        # 부스팅 라운드 수
    MAX_DEPTH: 6              # 트리의 최대 깊이
    LEARNING_RATE: 0.1        # 학습률
    SUBSAMPLE: 0.8            # 샘플링 비율
    COLSAMPLE_BYTREE: 0.8     # 피처 샘플링 비율
    REG_ALPHA: 0.1            # L1 정규화
    REG_LAMBDA: 1.0           # L2 정규화
    RANDOM_STATE: 42          # 랜덤 시드
    N_JOBS: -1                # 병렬 처리 스레드 수
    EARLY_STOPPING_ROUNDS: 50 # 조기 종료 라운드
    EVAL_METRIC: "rmse"       # 평가 메트릭
    
  # 피처 분류 설정 (chunk_eda_results.json 기반)
  FEATURES:
    CATEGORICAL:              # 실제 범주형 피처들 (categorical_stats)
      - "gender"
      - "age_group" 
      - "inventory_id"
      - "day_of_week"
      - "hour"
    NUMERICAL:                # 수치형 피처들 (numerical_stats에서 l_feat_20, l_feat_23 제외)
      # l_feat_*, feat_*, history_* 등 (l_feat_20, l_feat_23 제외)
    EXCLUDED:                 # 사용하지 않을 피처들
      - "l_feat_20"           # 상수값 (std=0.0)
      - "l_feat_23"           # 상수값 (std=0.0)
      - "seq"                 # 시퀀스 피처 (XGBoost에서 사용하지 않음)
    SEQUENTIAL: "seq"         # 시퀀스 피처 (사용하지 않음)

# 파일 경로 설정
PATHS:
  MODEL_SAVE: "trained_model_{datetime}.pth"
  TEMP_MODEL: "temp_model_{datetime}.pth"  # 임시 웨이트 파일
  RESULTS_DIR: "results_{datetime}"  # 날짜별 결과 디렉토리
  TRAIN_DATA: "data/train.parquet"  # 전체 데이터 사용
  TEST_DATA: "data/test.parquet"
