data:
  train_t_path: data/proc_train_t
  train_v_path: data/proc_train_v
  train_c_path: data/proc_train_c
  temp_dir: tmp
training: null
model:
  name: xgboost
xgboost:
  n_estimators: 84
  early_stopping_rounds: 20
  max_depth: 5
  learning_rate: 0.13066341322939076
  subsample: 1.0
  colsample_bytree: 0.5108367911454451
  scale_pos_weight: null
  gpu_id: 0
  verbosity: 0
  seed: 42
  tree_method: gpu_hist
  use_mixup: true
  mixup_alpha: 0.1
  mixup_ratio: 0.2
  min_child_weight: 18
  gamma: 1.2673867800210414
  reg_alpha: 0.2763580304884297
  reg_lambda: 2.6758321672210155
  max_bin: 164
  calibration_method: sigmoid
catboost:
  iterations: 200
  learning_rate: 0.28915714741018156
  depth: 8
  subsample: 1
  colsample_bylevel: 0.5779972601681014
  task_type: GPU
  devices: '0'
  verbose: false
  early_stopping_rounds: 20
  thread_count: -1
  random_seed: 42
  bootstrap_type: Bayesian
  use_mixup: false
  mixup_alpha: 0.3
  mixup_ratio: 0.5
  n_estimators: 218
  max_depth: 13
  random_state: 42
presets:
  xgboost:
    model:
      name: xgboost
  catboost:
    model:
      name: catboost
