name: toss-env
channels:
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.12

  # RAPIDS / cuDF (Python 3.12 지원은 24.10+부터)
  - cudf=24.12
  - cuda-version=12.4           # PyTorch CUDA와 맞춰 충돌 최소화

  # PyTorch (CUDA 12.4 빌드)
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4           # from nvidia channel

  # Data processing
  - pandas=2.2.*
  - numpy=1.26.*
  - scikit-learn=1.5.*

  # Utilities
  - pyyaml=6.*
  - tqdm=4.*
  - psutil=5.*

  # Data I/O
  - pyarrow=14.*                # RAPIDS와 궁합 좋은 범위 (너무 최신 고정은 충돌 유발)

  # Gradient boosting
  - xgboost=2.1.*
  - catboost=1.2.*

  # CUDA-python 생태계와 잘 맞는 CuPy
  - cupy=13.*