name: toss-env
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Python
  - python=3.11
  
  # Core ML/DL packages
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio>=2.0.0
  
  # Data processing
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.4.2
  
  # Configuration and utilities
  - pyyaml=6.0.2
  - tqdm=4.66.5
  - psutil=7.1.0
  
  # Model analysis and visualization
  - torchinfo=1.8.0
  
  # Data I/O
  - pyarrow=17.0.0
  
  # Gradient boosting
  - xgboost=2.1.3
  
  # NVIDIA packages (if needed)
  - nvtabular=23.08.00
  - cudf=23.10.0
  - cupy=13.6.0
  
  # Additional dependencies
  - pip
  - pip:
    # Any packages that need to be installed via pip
