name: toss-env
channels:
  - nvidia
  - rapidsai
  - numba
  - conda-forge
  - defaults

dependencies:
  # Python & RAPIDS stack (requires Python 3.10 for RAPIDS compatibility)
  - python=3.10
  
  # RAPIDS ecosystem (GPU-accelerated data science)
  - rapids         # cudf/dask-cudf/cuml/rmm/ucx 등 호환 세트
  - nvtabular
  - cupy
  
  # Core data science packages
  - numpy>=1.26.4
  - pandas
  - scikit-learn
  - pyarrow
  
  # GBDT models
  - xgboost
  - catboost
  
  # Utilities
  - psutil
  - dask
  - pyyaml
  - tqdm
  - pip>=23
  
  # Install PyTorch and related packages via pip for better GPU compatibility
  - pip:
      - torch
      - torchvision
      - lightning

